#NAME: Darren Lu                                           
#EMAIL: darrenlu3@ucla.edu
#ID: 205394473

build: dist

clean:
	rm -f lab4a-205394473.tar.gz

dist: README my_beaglebone.jpg connected.png copy.png build_run.png git.png Makefile
	tar -cvzf lab4a-205394473.tar.gz README my_beaglebone.jpg connected.png copy.png build_run.png git.png Makefile
